name = "Tokyo Night"
slug = "tokyo-night"
variant_label = "Tokyo Night"

[colors]
black = "0xff1a1b26"
white = "0xffc0caf5"
red = "0xfff7768e"
green = "0xff9ece6a"
blue = "0xff7aa2f7"
yellow = "0xffe0af68"
orange = "0xffff9e64"
magenta = "0xffbb9af7"
grey = "0xff565f89"
bg1 = "0xff1f2335"
bg2 = "0xff24283b"
bar_bg = "0x001a1b26"
bar_border = "0xff292e42"
popup_bg = "0xc01f2335"
popup_border = "0xff565f89"
